package probe

// NOTE: ExecObjects, LoadExecObjects, etc. are generated by bpf2go.
// Run `make generate` before building for the first time.

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"log"
	"strings"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"asec-agent/reporter"
)

// execEventRaw mirrors the C struct exec_event.
type execEventRaw struct {
	Pid      uint32
	Uid      uint32
	Comm     [16]byte
	Filename [256]byte
}

// ExecProbe loads the exec BPF program and emits ExecReport events.
type ExecProbe struct {
	objs     ExecObjects
	tp       link.Link
	reader   *ringbuf.Reader
	reporter *reporter.Reporter
}

func NewExecProbe(rep *reporter.Reporter) (*ExecProbe, error) {
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, err
	}

	objs := ExecObjects{}
	if err := LoadExecObjects(&objs, nil); err != nil {
		return nil, err
	}

	tp, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TraceExec, nil)
	if err != nil {
		objs.Close()
		return nil, err
	}

	reader, err := ringbuf.NewReader(objs.ExecEvents)
	if err != nil {
		tp.Close()
		objs.Close()
		return nil, err
	}

	return &ExecProbe{objs: objs, tp: tp, reader: reader, reporter: rep}, nil
}

func (p *ExecProbe) Run(ctx context.Context) {
	go func() {
		<-ctx.Done()
		p.reader.Close()
	}()

	for {
		record, err := p.reader.Read()
		if err != nil {
			return
		}

		var raw execEventRaw
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &raw); err != nil {
			log.Printf("exec: parse error: %v", err)
			continue
		}

		comm := nullTermStr(raw.Comm[:])
		filename := nullTermStr(raw.Filename[:])
		// Best-effort cmdline enrichment from /proc (may fail if process exits fast)
		cmdline := readCmdline(raw.Pid)

		evt := reporter.ExecReport{
			Pid:      raw.Pid,
			Uid:      raw.Uid,
			Comm:     comm,
			Filename: filename,
			Args:     cmdline,
		}
		p.reporter.QueueExec(evt)

		// Alert: shell spawned by a server process
		if serverProcs[comm] && shellExecs[filename] {
			detail, _ := json.Marshal(map[string]any{
				"parent_comm": comm,
				"shell":       filename,
				"cmdline":     cmdline,
			})
			p.reporter.QueueAlert(reporter.ProcessAlert{
				AlertType: "shell_from_server",
				Severity:  "critical",
				Pid:       raw.Pid,
				Comm:      comm,
				Detail:    string(detail),
			})
		}

		// Alert: execution from temp/writeable directories
		for _, prefix := range []string{"/tmp/", "/dev/shm/", "/var/tmp/"} {
			if strings.HasPrefix(filename, prefix) {
				detail, _ := json.Marshal(map[string]any{
					"filename": filename,
					"cmdline":  cmdline,
					"reason":   "execution from writable directory",
				})
				p.reporter.QueueAlert(reporter.ProcessAlert{
					AlertType: "exec_from_tmp",
					Severity:  "high",
					Pid:       raw.Pid,
					Comm:      comm,
					Detail:    string(detail),
				})
				break
			}
		}
	}
}

func (p *ExecProbe) Close() {
	p.reader.Close()
	p.tp.Close()
	p.objs.Close()
}
