package probe

// NOTE: FlowObjects, loadFlowObjects, etc. are generated by bpf2go.
// Run `make generate` before building for the first time.

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"log"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"asec-agent/reporter"
)

// flowEventRaw mirrors the C struct flow_event (little-endian layout).
type flowEventRaw struct {
	Pid       uint32
	Uid       uint32
	Comm      [16]byte
	Saddr     uint32
	Daddr     uint32
	Sport     uint16
	Dport     uint16
	Direction uint8
	_         [3]byte
}

// FlowProbe loads the flow BPF program and emits FlowReport events.
type FlowProbe struct {
	objs     FlowObjects
	tp       link.Link
	reader   *ringbuf.Reader
	reporter *reporter.Reporter
}

func NewFlowProbe(rep *reporter.Reporter) (*FlowProbe, error) {
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, err
	}

	objs := FlowObjects{}
	if err := loadFlowObjects(&objs, nil); err != nil {
		return nil, err
	}

	tp, err := link.Tracepoint("sock", "inet_sock_set_state", objs.TraceFlow, nil)
	if err != nil {
		objs.Close()
		return nil, err
	}

	reader, err := ringbuf.NewReader(objs.FlowEvents)
	if err != nil {
		tp.Close()
		objs.Close()
		return nil, err
	}

	return &FlowProbe{objs: objs, tp: tp, reader: reader, reporter: rep}, nil
}

func (p *FlowProbe) Run(ctx context.Context) {
	go func() {
		<-ctx.Done()
		p.reader.Close()
	}()

	for {
		record, err := p.reader.Read()
		if err != nil {
			return
		}

		var raw flowEventRaw
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &raw); err != nil {
			log.Printf("flow: parse error: %v", err)
			continue
		}

		comm := nullTermStr(raw.Comm[:])
		srcIP := uint32ToIPStr(raw.Saddr)
		dstIP := uint32ToIPStr(raw.Daddr)

		flow := reporter.FlowReport{
			Pid:       raw.Pid,
			Uid:       raw.Uid,
			Comm:      comm,
			SrcIP:     srcIP,
			DstIP:     dstIP,
			SrcPort:   raw.Sport,
			DstPort:   raw.Dport,
			Direction: raw.Direction,
		}
		p.reporter.QueueFlow(flow)

		// Alert detection: outbound to suspicious port or from a server process to external IP
		if raw.Direction == 0 {
			if desc, bad := suspiciousDstPorts[raw.Dport]; bad {
				detail, _ := json.Marshal(map[string]any{
					"dst_ip": dstIP, "dst_port": raw.Dport, "reason": desc,
				})
				p.reporter.QueueAlert(reporter.ProcessAlert{
					AlertType: "suspicious_outbound_port",
					Severity:  "high",
					Pid:       raw.Pid,
					Comm:      comm,
					DstIP:     dstIP,
					DstPort:   raw.Dport,
					Detail:    string(detail),
				})
			} else if !isPrivateIP(dstIP) && serverProcs[comm] {
				detail, _ := json.Marshal(map[string]any{
					"dst_ip": dstIP, "dst_port": raw.Dport,
					"reason": "server process making outbound external connection",
				})
				p.reporter.QueueAlert(reporter.ProcessAlert{
					AlertType: "server_unexpected_outbound",
					Severity:  "medium",
					Pid:       raw.Pid,
					Comm:      comm,
					DstIP:     dstIP,
					DstPort:   raw.Dport,
					Detail:    string(detail),
				})
			}
		}
	}
}

func (p *FlowProbe) Close() {
	p.reader.Close()
	p.tp.Close()
	p.objs.Close()
}
